#sonar.projectkey=Akshat-Rule
#sonar.projectname=Akshat-Rule
#sonar.java.binaries=.


sonar.projectKey=github-action-cicd
sonar.projectName=GitHub Action CICD
sonar.projectVersion=1.0

sonar.sources=src
sonar.java.binaries=target
